export const payment = [
  {
    id: 1,
    trainerName: "Ahmed Adel",
    courseName: "Course 1",
    status: "Not Paid",
    method: "Visa",
    amount: 5000,
    date: "12/12/2021",
  },
  {
    id: 2,
    trainerName: "John Doe",
    courseName: "Course 2",
    status: "Paid",
    method: "Paypal",
    amount: 3000,
    date: "01/15/2022",
  },
  {
    id: 3,
    trainerName: "Jane Smith",
    courseName: "Course 3",
    status: "Not Paid",
    method: "Cash",
    amount: 4500,
    date: "02/20/2022",
  },
  {
    id: 4,
    trainerName: "Emily Johnson",
    courseName: "Course 4",
    status: "Paid",
    method: "Master Card",
    amount: 6000,
    date: "03/10/2022",
  },
  {
    id: 5,
    trainerName: "Michael Brown",
    courseName: "Course 5",
    status: "Not Paid",
    method: "Visa",
    amount: 2500,
    date: "04/05/2022",
  },
  {
    id: 6,
    trainerName: "Chris Davis",
    courseName: "Course 6",
    status: "Paid",
    method: "Paypal",
    amount: 7000,
    date: "05/18/2022",
  },
  {
    id: 7,
    trainerName: "Patricia Wilson",
    courseName: "Course 7",
    status: "Not Paid",
    method: "Cash",
    amount: 3200,
    date: "06/22/2022",
  },
];
